### ISSUE TITLE
Tutorial says needs .net 6 but project in .net 5

### ISSUE THREAD

**Issue by Thebe01** [MicrosoftDocs/mslearn-build-interactive-components-blazor#1]
The project has the wrong version of .net. Should be upgraded to .net 6.

**Comment by arafat-pro** [comment]
Is there any way to continue the [exercise](https://learn.microsoft.com/en-us/training/modules/blazor-build-rich-interactive-components/3-exercise-use-javascript-libraries-blazor-apps)?

**Comment by Terryio** [comment]
I have same issue.
To change .NET version, I change BlazingPizza.csproj file with this : 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.13" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
  </ItemGroup>

</Project>
```

And update .NET version on .vscode/launch.json file in line 13 : 
`            "program": "${workspaceFolder}/bin/Debug/net6.0/BlazingPizza.dll",`
