### ISSUE TITLE
Missing information in tutorial unit 5

### ISSUE THREAD

**Issue by Thebe01** [MicrosoftDocs/mslearn-build-interactive-components-blazor#4]
The unit 5 tutorial is missing information on where to write some pieces of code.

In Fix the Price and Size:
Step4 should specify that the code is to be written in OrderState.cs
Step 6 should specify that the code is to be written in OrderDetail.razor

**Comment by arafat-pro** [comment]
OrderState.cs is not inside the Model folder as stated!
-
![image](https://user-images.githubusercontent.com/3014435/211990689-f7e6d28d-3cb0-4f55-af03-c5ed8e55ee6f.png)

**Comment by arafat-pro** [comment]
> OrderDetail.razor

Step 6 was ok for me as stated [ConfigurePizzaDialog.razor in the document](https://learn.microsoft.com/en-us/training/modules/blazor-build-rich-interactive-components/5-exercise-improve-app-interactivity-lifecycle-events)
