### ISSUE TITLE
Place Order stopped working after adding new Pizza

### ISSUE THREAD

**Issue by johnmathewii** [MicrosoftDocs/mslearn-build-interactive-components-blazor#7]
In the Unit 5 of Module 7 where the user adds a new Pizza of size 24 and make certain changes to the slider, price and size of the pizza. After following everything the tutorial suggested the part where the address is filled and the order placed the app is not placing the order instead gives an error in the browser  "An unhandled exception has occurred. See browser dev tools for details. [Reload](http://localhost:5000/)" to any pizza selected

**Comment by arafat-pro** [comment]
For this problem "Exercise - Reuse components by creating templates" cannot be practiced at learner's end!
